# yaml pour les tests

version: 2

models:
  - name: stg_etudiants
    description: "Données étudiants nettoyées et standardisées"
    
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - USER_ID
            - YEAR_PATH_STARTED

    columns:
      - name: USER_ID
        description: "Identifiant unique"
        tests:  
          - not_null     
      
      - name: AGE_GROUP
        description: "Tranche d'âge"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: 
                  - '20-24 ans'
                  - '25-29 ans'
                  - '30-34 ans'
                  - '35-39 ans'
                  - '40-44 ans'
                  - '45-49 ans'
                  - '50-54 ans'
                  - '55-59 ans'
                  - '60 ans ou plus'
      
      - name: GENDER
        description: "Genre (après traitement des valeurs manquantes)"
        tests:
          - not_null  
          - accepted_values:
              arguments:
                values: 
                  - 'F'
                  - 'M'
                  - 'Non renseigné'
      
      - name: YEAR_PATH_STARTED
        description: "Année de début"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: 
                  - 2022
                  - 2023
                  - 2024 
                  - 2025

      - name: REGION
        tests:
          - not_null


  - name: etudiants_OC__population_insee
    description: "Données finalisée de comparaison entre les données OC et les données INSEE"
    
    tests:
      - dbt_utils.unique_combination_of_columns:
         combination_of_columns:
            - REGION
            - GENDER
            - AGE_GROUP
            - ANNEE
 
    columns:
      - name: REGION
        tests:
          - not_null

      - name: GENDER
        tests:
          - not_null

      - name: AGE_GROUP
        tests:
          - not_null

      - name: ANNEE
        tests:
          - not_null

      - name: NB_ETUDIANTS
        tests:
          - not_null

      - name: POPULATION
        tests:
          - not_null
