# Yaml concernant les sources et les descriptions

version: 2

sources:
  - name: raw_data
    description: "Données brutes importées dans Snowflake"
    database: P8_OPENCLASSROOMS
    schema: RAW_DATA
    tables:
      - name: ETUDIANTS
        description: "Données sociodémographiques des étudiants Data OC"
        columns:
          - name: USER_ID
            description: "Identifiant technique unique de l'étudiant"
          - name: PATH_CATEGORY_NAME
            description: "Catégorie du parcours suivi (Data)"
          - name: AGE_GROUP
            description: "Classe d'âge au moment du début du parcours"
          - name: GENDER
            description: "Genre déclaré par l'étudiant (F/M ou vide)"
          - name: REGION
            description: "Région de résidence"
          - name: YEAR_PATH_STARTED
            description: "Année de début du parcours"

      - name: POPULATION_INSEE_2022
        description: "Données de l'INSEE par catégories d'âges et sexe pour 2022"
        columns:
          - name: AGE_GROUP
            description: "Classe d'âge"
          - name: GENDER
            description: "Genre déclaré (F ou H)"
          - name: POPULATION
            description: "Nombre d'individus"
          - name : ANNEE
            description: "Année du recensement"

      - name: POPULATION_INSEE_2023 
        description: "Données de l'INSEE par catégories d'âges et sexe pour 2023"
        columns:
          - name: AGE_GROUP
            description: "Classe d'âge"
          - name: GENDER
            description: "Genre déclaré (F ou H)"
          - name: POPULATION
            description: "Nombre d'individus"
          - name : ANNEE
            description: "Année du recensement"

      - name: POPULATION_INSEE_2024 
        description: "Données de l'INSEE par catégories d'âges et sexe pour 2024"
        columns:
          - name: AGE_GROUP
            description: "Classe d'âge"
          - name: GENDER
            description: "Genre déclaré (F ou H)"
          - name: POPULATION
            description: "Nombre d'individus"
          - name : ANNEE
            description: "Année du recensement"

      - name: POPULATION_INSEE_2025 
        description: "Données de l'INSEE par catégories d'âges et sexe pour 2025"
        columns:
          - name: AGE_GROUP
            description: "Classe d'âge"
          - name: GENDER
            description: "Genre déclaré (F ou H)"
          - name: POPULATION
            description: "Nombre d'individus"
          - name : ANNEE
            description: "Année du recensement"